repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-json

repos:
-   repo: https://github.com/triciahf/sen_pre_commit_hooks
    rev: main
    hooks:
    - id: check-yaml-format
      exclude: (.pre-commit-config.yaml)      